-- liquibase formatted sql
-- changeset Vasiliy:1

CREATE table event_table(
    id BIGINT primary key generated by default as identity not null,
    title varchar,
    event_id BIGINT,
    prices varchar,
    sales_status varchar,
    localised_start_date varchar,
    localised_end_date varchar,
    salestart varchar,
    promoter_id BIGINT,
    min_price BIGINT,
    short_url varchar,
    short_image_url varchar,
    type varchar,
    special_status varchar,
    source varchar);

ALTER TABLE event_table
    ADD venue_id BIGINT;