-- liquibase formatted sql
-- changeset Vasiliy:11

CREATE TABLE unknown_new_events(
    id BIGINT generated by default as identity not null,
    title varchar,
    venue_description varchar,
    venue_id BIGINT
);