-- liquibase formatted sql
-- changeset Vasiliy:13

-- Миграция таблиц с театрами! Не забудь внести эту миграцию в ченджлог!

create table venue_table
(
    id                bigint generated by default as identity
        primary key,
    venue_description varchar
);

alter table venue_table
    owner to postgres;

INSERT INTO public.venue_table (id, venue_description) VALUES (1, 'Белгосцирк');
INSERT INTO public.venue_table (id, venue_description) VALUES (2, 'Белорусский государственный музыкальный театр');
INSERT INTO public.venue_table (id, venue_description) VALUES (3, 'Большой театр Беларуси');
INSERT INTO public.venue_table (id, venue_description) VALUES (4, 'Брестский академический театр драмы');
INSERT INTO public.venue_table (id, venue_description) VALUES (5, 'Гомельский государственный театр кукол');
INSERT INTO public.venue_table (id, venue_description) VALUES (6, 'Гомельский областной драматический театр');
INSERT INTO public.venue_table (id, venue_description) VALUES (7, 'Гомельский областной общественно-культурный центр');
INSERT INTO public.venue_table (id, venue_description) VALUES (8, 'Гродненская областная филармония');
INSERT INTO public.venue_table (id, venue_description) VALUES (9, 'ДК Мозырский НПЗ');
INSERT INTO public.venue_table (id, venue_description) VALUES (10, 'ДК Барановичи');
INSERT INTO public.venue_table (id, venue_description) VALUES (11, 'ДК Солигорск');
INSERT INTO public.venue_table (id, venue_description) VALUES (12, 'ДК Железнодорожников, Витебск');
INSERT INTO public.venue_table (id, venue_description) VALUES (13, 'ДК Нафтан');
INSERT INTO public.venue_table (id, venue_description) VALUES (14, 'ДК Железнодорожников, Орша');
INSERT INTO public.venue_table (id, venue_description) VALUES (15, 'ДК им.Горького, Борисов');
INSERT INTO public.venue_table (id, venue_description) VALUES (16, 'ДК БелАз, Жодино');
INSERT INTO public.venue_table (id, venue_description) VALUES (17, 'Драматический театр Белорусской армии, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (18, 'Концертный зал Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (19, 'Минский областной драматический театр, Молодечно');
INSERT INTO public.venue_table (id, venue_description) VALUES (20, 'Молодежный театр эстрады, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (21, 'Молодежный театр, Гомель');
INSERT INTO public.venue_table (id, venue_description) VALUES (22, 'Молодежный театр, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (23, 'Театр имени Якуба Коласа, Витебск');
INSERT INTO public.venue_table (id, venue_description) VALUES (24, 'Областной общественно-культурный центр, Брест');
INSERT INTO public.venue_table (id, venue_description) VALUES (25, 'Областной центр творчества, Могилев');
INSERT INTO public.venue_table (id, venue_description) VALUES (26, 'Пинский Городской Дом Культуры');
INSERT INTO public.venue_table (id, venue_description) VALUES (27, 'Дворец культуры профсоюзов, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (28, 'Слуцкий городской Дом культуры');
INSERT INTO public.venue_table (id, venue_description) VALUES (29, 'ДК Театр-студия Киноактера, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (30, 'Театр имени Максима Горького, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (31, 'Театр имени Янки Купалы, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (32, 'Театр юного зрителя, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (33, 'Центральный Дом офицеров, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (34, 'Гомельская областная филармония');
INSERT INTO public.venue_table (id, venue_description) VALUES (35, 'Двор\Зал замка Радзивиллов, Несвиж');
INSERT INTO public.venue_table (id, venue_description) VALUES (36, 'ДК культуры области, Могилев');
INSERT INTO public.venue_table (id, venue_description) VALUES (37, 'Центр культуры, Полоцк');
INSERT INTO public.venue_table (id, venue_description) VALUES (38, 'ДК Молодечно');
INSERT INTO public.venue_table (id, venue_description) VALUES (39, 'Дворец Республики, Минск');
INSERT INTO public.venue_table (id, venue_description) VALUES (40, 'Концертный зал, Витебск');




create table venue_directory_table
(
    id                bigint generated by default as identity
        primary key,
    venue_description varchar,
    venue_id          bigint
);

alter table venue_directory_table
    owner to postgres;

INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (46, 'Белгосцирк, Минск', 1);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (47, 'Белорусский гос. музыкальный театр, Минск', 2);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (48, 'Белорусский гос.музыкальный театр, Минск', 2);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (49, 'Большой театр Беларуси /  The Bolshoi Theatre of Belarus, Минск', 3);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (50, 'Большой театр Беларуси, камерный зал / The Bolshoi Theatre of Belarus, Chamber Hall, Минск', 3);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (51, 'Брестский академический театр драмы, Брест', 4);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (52, 'Брестский академический театр драмы, малый зал, Брест', 4);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (53, 'Брестский академический театр драмы, Малый зал, Брест', 4);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (54, 'Брестский академический театр драмы, Театральный бар, Брест', 4);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (55, 'Гомельский государственный театр кукол, Гомель', 5);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (56, 'Гомельский Областной Драматический Театр, Гомель', 6);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (57, 'Гомельский областной общественно-культурный центр, Гомель', 7);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (58, 'Гродненская областная филармония, Гродно', 8);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (59, 'Дворец Культуры ''''Мозырский НПЗ'''', Мозырь', 9);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (60, 'Дворец культуры г. Барановичи, Барановичи', 10);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (61, 'Дворец культуры г. Солигорск, Солигорск', 11);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (62, 'Дворец культуры железнодорожников, г. Витебск, Витебск', 12);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (63, 'ДК ''''Нафтан'''', Новополоцк', 13);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (64, 'ДК Железнодорожников ''''Орша'''', Орша', 14);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (65, 'ДК им. Горького, г.Борисов, Борисов', 15);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (66, 'ДК ОАО ''''БелАЗ'''', Жодино', 16);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (67, 'Драматический театр Белорусской армии, Минск', 17);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (68, 'КЗ ''''Минск'''' (малый зал), Минск', 18);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (69, 'Концертный зал Минск, Минск', 18);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (70, 'Минский областной драматический театр, Молодечно', 19);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (71, 'Молодежный театр эстрады, Минск', 20);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (72, 'Молодежный театр, г. Гомель, Гомель', 21);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (73, 'Молодежный театр, малый зал, Минск', 22);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (74, 'Молодежный театр, Минск', 22);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (75, 'НАДТ им. Якуба Коласа, Камерная сцена, Витебск', 23);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (76, 'НАДТ имени Якуба Коласа, камерная сцена, Витебск', 23);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (77, 'НАДТ имени Якуба Коласа, Камерная сцена, Витебск', 23);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (78, 'Национальный театр имени Якуба Коласа, Витебск', 23);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (79, 'Областной общественно-культурный центр, Брест', 24);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (80, 'Областной центр творчества г. Могилева, Могилев', 25);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (81, 'Пинский Городской Дом Культуры, Пинск', 26);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (82, 'Республиканский дворец культуры профсоюзов, Минск', 27);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (83, 'Слуцкий городской Дом культуры, Слуцк', 28);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (84, 'Театр-студия Киноактера (пр-т Машерова, 33), Минск', 29);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (85, 'Театр имени Максима Горького, Малая сцена, Минск', 30);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (86, 'Театр имени Максима Горького, Минск', 30);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (87, 'Театр имени Янки Купалы, камерная сцена, Минск', 31);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (88, 'Театр имени Янки Купалы, Минск', 31);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (89, 'Театр имени Янки Купалы. Камінная зала, Минск', 31);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (90, 'Театр юного зрителя, Минск', 32);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (91, 'Центральный Дом офицеров, Минск', 33);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (92, 'КЗ ГУ ''''Гомельская областная филармония'''', Гомель', 34);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (97, 'ГУК Центр культуры ''''Полоцк'''', Полоцк', 37);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (96, 'ГУК Центр культуры Полоцк', 37);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (93, 'г.НЕСВИЖ, центральный двор замка Радзивиллов, Несвиж', 35);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (99, 'Дворец Республики. Малый зал., Минск', 39);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (95, 'ГУК Дворец культуры области, г. Могилев, Могилев', 36);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (100, 'КЗ ''''Витебск'''', Витебск', 40);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (94, 'г. Несвиж, театральный зал в Дворцовом ансамбле / Nesvizh, Theatre Hall of the Radziwill Castle , Несвиж', 35);
INSERT INTO public.venue_directory_table (id, venue_description, venue_id) VALUES (98, 'Дворец культуры, г. Молодечно, Молодечно', 38);
