-- liquibase formatted sql
-- changeset Vasiliy:4


CREATE TABLE venue_directory_table(
     id BIGINT primary key generated by default as identity not null,
     venue_description varchar,
     venue_id BIGINT);


