-- liquibase formatted sql
-- changeset Vasiliy:5

CREATE TABLE saved_filter(
    id BIGINT primary key generated by default as identity not null,
    user_name varchar,
    event_id BIGINT
);

ALTER TABLE saved_filter
    ADD COLUMN venue_id BIGINT;