-- liquibase formatted sql
-- changeset Vasiliy:7

CREATE TABLE event_name(
    id BIGINT primary key generated by default as identity not null,
    title varchar);


CREATE TABLE event_name_directory(
    id BIGINT primary key generated by default as identity not null,
    event_id BIGINT,
    title varchar,
    event_name_id BIGINT);

